name: Build & deploy

on:
  push:
    branches:
      - development-api

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache modules
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Use Node.js 16.14.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.0

      - name: "Setup .env"
        run: |
          touch .env
          echo 'NEXT_PUBLIC_APP_ENV=production' >> .env
          echo 'NEXT_PUBLIC_NODE_ENV=testnet' >> .env
          echo 'NEXT_PUBLIC_TESTNET_CHAINID=0x534e5f474f45524c49' >> .env
          echo 'NEXT_PUBLIC_MAINNET_CHAINID=0x534e5f4d41494e' >> .env
          echo 'NEXT_PUBLIC_GOOGLE_SHEET_ID_SUGGESTIONS=1izyJKiQ5V2Ac8Yte6LOnVa2AFtGexASrEIUULHqbBvM' >> .env
          echo 'NEXT_PUBLIC_GOOGLE_SHEET_ID_BUGS=1IbDqMPz7S6haGe2aj4cvOfNAcGv6ckRo6nLAE3ngEMc' >> .env
          echo 'NEXT_PUBLIC_GOOGLE_SHEET_ID=1wrfZVXCdDHgemM3kfTRe4HPAJdhYLm90z8GHXd_AOTw' >> .env
          echo 'NEXT_PUBLIC_METRICS_API=https://n4mqvzurra.execute-api.ap-southeast-1.amazonaws.com/' >> .env
          echo 'NEXT_PUBLIC_MIXPANEL_KEY=${{secrets.NEXT_PUBLIC_MIXPANEL_KEY_DEV}}' >> .env
          echo 'NEXT_PUBLIC_GOOGLE_CLIENT_EMAIL=${{secrets.NEXT_PUBLIC_GOOGLE_CLIENT_EMAIL_DEV}}' >> .env
          echo 'NEXT_PUBLIC_GOOGLE_PRIVATE_KEY=${{secrets.NEXT_PUBLIC_GOOGLE_PRIVATE_KEY_DEV}}' >> .env
          echo 'NEXT_PUBLIC_AWS_ACCESS_KEY_ID=${{secrets.NEXT_PUBLIC_AWS_ACCESS_KEY_ID_DEV}}' >> .env
          echo 'NEXT_PUBLIC_AWS_SECRET_ACCESS_KEY=${{secrets.NEXT_PUBLIC_AWS_SECRET_ACCESS_KEY_DEV}}' >> .env

      - name: Accessing the cer
        run: |
          echo '${{secrets.AWS_ACCESS_KEY_CER}}' >> deployer.cer && chmod 600 deployer.cer

      - name: Stopping the application instance
        run: |
          ssh -o StrictHostKeyChecking=no -i deployer.cer ubuntu@ec2-13-212-154-59.ap-southeast-1.compute.amazonaws.com './stop_service.sh'
          echo "PM2 service stopped ⚠️"

      - name: Zipping and sending
        run: |
          zip -r release.zip .
          scp -o StrictHostKeyChecking=no -i deployer.cer release.zip ubuntu@ec2-13-212-154-59.ap-southeast-1.compute.amazonaws.com:/home/ubuntu/release.zip
          echo "Zip sent ✅"

      - name: Building local - AWS
        run: |
          ssh -o StrictHostKeyChecking=no -i deployer.cer ubuntu@ec2-13-212-154-59.ap-southeast-1.compute.amazonaws.com 'unzip release.zip -d ./release'
          echo "Unzip done ✅"
          ssh -o StrictHostKeyChecking=no -i deployer.cer ubuntu@ec2-13-212-154-59.ap-southeast-1.compute.amazonaws.com 'cd release && yarn'
          echo "Dependencies Installed !!! ✅"

      - name: Running the service
        run: |
          ssh -o StrictHostKeyChecking=no -i deployer.cer ubuntu@ec2-13-212-154-59.ap-southeast-1.compute.amazonaws.com 'yarn build && pm2 start yarn -- start'
