name: Build & deploy

on:
  push:
    branches:
      - sepolia-changes-actions-workflow
      - sepolia-changes-actions-workflow-test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache modules
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      # clone itachi-sdk build in v1-client

      - name: Clone SDK Repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          owner: '0xHashstack'
          repository: 'v1-sdk-itachi'
          access-token: ${{ secrets.REPO_PAT }}
        
      - name: Build SDK
        run: |
          cd v1-sdk-itachi
          yarn install
          yarn run build:iife
          yarn run build:dts
          yarn pack --filename sdk_build.tgz
    
      - name: Move SDK Tarball
        run: |
           mv v1-sdk-itachi/sdk_build.tgz ./sdk_build.tgz
    
      - name: Install SDK in Frontend
        run: |
          yarn add ./sdk_build.tgz

      - name: Use Node.js 16.14.0
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: Install dependencies
        run: yarn
      
      - name: "Setup .env"
        run: |
          touch .env
          echo 'NEXT_PUBLIC_APP_ENV=production' >> .env
          echo 'NEXT_PUBLIC_NODE_ENV=testnet' >> .env
          echo 'NEXT_PUBLIC_TESTNET_CHAINID=0x534e5f474f45524c49' >> .env
          echo 'NEXT_PUBLIC_MAINNET_CHAINID=0x534e5f4d41494e' >> .env
          echo 'NEXT_PUBLIC_METRICS_API=https://5c8l45vyxb.execute-api.ap-southeast-1.amazonaws.com/' >> .env
          echo 'NEXT_PUBLIC_MIXPANEL_KEY=${{secrets.NEXT_PUBLIC_MIXPANEL_KEY_DEV}}' >> .env
          echo 'NEXT_PUBLIC_INFURA_MAINNET=${{secrets.NEXT_PUBLIC_INFURA_MAINNET}}' >> .env
          echo 'NEXT_PUBLIC_INFURA_TESTNET=${{secrets.NEXT_PUBLIC_INFURA_TESTNET}}' >> .env
          echo 'NEXT_PUBLIC_FEEDBACK_API=${{secrets.NEXT_PUBLIC_FEEDBACK_API}}' >> .env
          echo 'NEXT_PUBLIC_POSTHOG_KEY=${{secrets.NEXT_PUBLIC_POSTHOG_KEY}}' >> .env
          echo 'NEXT_PUBLIC_HOSTHOG_HOST=${{secrets.NEXT_PUBLIC_HOSTHOG_HOST}}' >> .env
    
      - name: Build
        run: yarn build
      - name: Export
        run: yarn export
        
