name: Build & deploy [Mainnet]

on:
    push:
        branches:
            - mainnet-V1
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Cache modules
              uses: actions/cache@v4
              id: yarn-cache
              with:
                  path: node_modules
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: ${{ runner.os }}-yarn-
            - name: Use Node.js 20
              uses: actions/setup-node@v1
              with:
                  node-version: 20
            - name: 'Setup .env'
              run: |
                  touch .env
                  echo 'NEXT_PUBLIC_APP_ENV=production' >> .env
                  echo 'NEXT_PUBLIC_NODE_ENV=mainnet' >> .env
                  echo 'NEXT_PUBLIC_TESTNET_CHAINID=0x534e5f474f45524c49' >> .env
                  echo 'NEXT_PUBLIC_MAINNET_CHAINID=0x534e5f4d41494e' >> .env
                  echo 'NEXT_PUBLIC_METRICS_API=https://metricsapimainnet.hashstack.finance' >> .env
                  echo 'NEXT_PUBLIC_MIXPANEL_KEY=${{secrets.NEXT_PUBLIC_MIXPANEL_KEY_MAINNET}}' >> .env
                  echo 'NEXT_PUBLIC_ALCHEMY_MAINNET=${{secrets.NEXT_PUBLIC_ALCHEMY_MAINNET}}' >> .env
                  echo 'NEXT_PUBLIC_INFURA_MAINNET=${{secrets.NEXT_PUBLIC_INFURA_MAINNET}}' >> .env
                  echo 'NEXT_PUBLIC_INFURA_TESTNET=${{secrets.NEXT_PUBLIC_INFURA_TESTNET}}' >> .env
                  echo 'NEXT_PUBLIC_FEEDBACK_API=https://metricsapimainnet.hashstack.finance' >> .env
                  echo 'NEXT_PUBLIC_POSTHOG_KEY=${{secrets.NEXT_PUBLIC_POSTHOG_KEY}}' >> .env
                  echo 'NEXT_PUBLIC_HOSTHOG_HOST=${{secrets.NEXT_PUBLIC_HOSTHOG_HOST}}' >> .env

            - name: Install dependencies
              run: yarn
            
            - name: Setup Pages
              uses: actions/configure-pages@v5
              with:
                  static_site_generator: next
            
            - name: Build
              run: |
                  export NODE_OPTIONS=--max_old_space_size=8192
                  NEXT_PUBLIC_APP_ENV=production yarn build

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: ./out

    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
